### PR TITLE
Add support for host tags.

### PR DESCRIPTION
**Pull request by dilijev**

### CODE REVIEW

**Comment by dilijev** [comment]
Currently requires manually editing the config file. If the general feeling is that this is a useful idea, I can add syntax to adding a host to make this easier for setup.

**Comment by dilijev** [comment]
@bterlson Is it okay that the CI is failing?

**Comment by bterlson** [comment]
@jugglinmike @rwaldron can you take a look at travis? I'm not sure what's going on here...

**Comment by jugglinmike** [comment]
It looks like TravisCI has recently been enabled for this project (the failing
build is only the second ever run), but the project itself has not been
extended with a `.travis.yml` file. The error we're seeing is a result of the
TravisCI service running with all defaults--in the absence of a `.travis.yml`
file, it assumes this is a Ruby-based project and attempts to use the generic
command `rake test` to validate the pull request. This fails, of course, and
that's what the log is reporting.

The failure can be safely ignored, but to limit noise, the TravisCI service
should be disabled for this project. Once the project has tests (nudge nudge),
TravisCI can be re-enabled to run those.

**Comment by bterlson** [comment]
@jugglinmike gah damnit, I forgot which project I was in. Yes, I will disable Travis for now. Tests are needed (though I wish testing this project weren't so difficult).

**Comment by rwaldron** [comment]
> Tests are needed

I might take on writing some initial tests.

**Comment by rwaldron** [comment]
While writing tests, I discovered that this doesn't actually provide a way to set `tags` for a host during `--add` operation.

**Comment by rwaldron** [comment]
I will have a fix for that shortly.

**Comment by dilijev** [comment]
Yep, in my first comment:

> If the general feeling is that this is a useful idea, I can add syntax to adding a host to make this easier for setup.

I meant to add this to the PR if people liked the idea. Follow-up PR is good too. Thanks @rwaldron

**Comment by rwaldron** [comment]
Oh, I must've read that and just forgot :\

**Pull request merged**
